import { Network, Currencies } from '@cryptodo/contracts';

import { NetworkMeta } from '@/types';
import {
  BinanceLogoIcon,
  EthereumLogoIcon,
  PolygonLogoIcon,
  AuroraLogoIcon,
  OptimismLogoIcon,
  AvalancheLogoIcon,
  MantleLogoIcon,
  OKCLogoIcon,
  BitgertLogoIcon,
  FiveIreLogoIcon,
  ShardeumLogoIcon,
  EvmOsLogoIcon,
  BitTorrentLogoIcon,
  GateLogoIcon,
  FantomLogoIcon,
  LightlinkLogoIcon,
  ZetaLogoIcon,
  CronosLogoIcon,
  ArbitrumLogoIcon,
  NautilusLogoIcon,
  EosEvmLogoIcon,
  BaseLogoIcon,
  ArtheraLogoIcon,
} from '@/assets/icons';

export const networksMeta: { [network in Network]: NetworkMeta } = {
  [ Network.ethereum ]: {
    name: 'Ethereum',
    symbol: 'ETH',
    logo: <EthereumLogoIcon />,
    description: 'Ethereum',
  },
  [ Network.bsc ]: {
    name: 'BNB Chain',
    symbol: Currencies.bnb,
    logo: <BinanceLogoIcon />,
    description: 'BNB Chain',
  },
  [ Network.polygon ]: {
    name: 'Polygon',
    symbol: 'MATIC',
    logo: <PolygonLogoIcon />,
    description: 'Polygon',
  },
  [ Network.aurora ]: {
    name: 'Aurora',
    symbol: 'ETH',
    logo: <AuroraLogoIcon />,
    description: 'Aurora',
  },
  [ Network.optimism ]: {
    name: 'Optimism',
    symbol: 'ETH',
    logo: <OptimismLogoIcon />,
    description: 'Optimism',
  },
  [ Network.avalanche ]: {
    name: 'Avalance',
    symbol: 'AVAX',
    logo: <AvalancheLogoIcon />,
    description: 'Avalancle',
  },
  [ Network.mantle ]: {
    paymentsDisabled: false,
    name: 'Mantle',
    symbol: 'MNT',
    logo: <MantleLogoIcon />,
    description: 'Mantle',
  },
  [ Network.okc ]: {
    paymentsDisabled: false,
    name: 'OKT',
    symbol: 'OKT',
    logo: <OKCLogoIcon />,
    description: 'OKT Chain',
  },
  [ Network.bitgert ]: {
    paymentsDisabled: false,
    name: 'Bitgert',
    symbol: 'Brise',
    logo: <BitgertLogoIcon />,
    description: 'Bitgert Chain',
  },
  [ Network.fiveIre ]: {
    paymentsDisabled: true,
    name: '5ire',
    symbol: '5ire',
    logo: <FiveIreLogoIcon />,
    description: '5ire',
  },
  [ Network.bitTorrent ]: {
    paymentsDisabled: false,
    name: 'BitTorrent',
    symbol: 'BTT',
    logo: <BitTorrentLogoIcon />,
    description: 'BitTorrent',
  },
  [ Network.gate ]: {
    paymentsDisabled: false,
    name: 'Gate Chain',
    symbol: 'GT',
    logo: <GateLogoIcon />,
    description: 'Gate Chain',
  },
  [ Network.evmOs ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Evmos',
    symbol: 'EVMOS',
    logo: <EvmOsLogoIcon />,
    description: 'Evmos',
  },
  [ Network.lightlink ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Lightlink',
    symbol: 'ETH',
    logo: <LightlinkLogoIcon />,
    description: 'Lightlink',
  },
  [ Network.zetaChain ]: {
    paymentsDisabled: true,
    disabled: false,
    name: 'Zeta Chain',
    symbol: 'ZETA',
    logo: <ZetaLogoIcon />,
    description: 'Zeta Chain',
  },
  [ Network.fantom ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Fantom',
    symbol: 'FTM',
    logo: <FantomLogoIcon />,
    description: 'Fantom',
  },
  [ Network.cronos ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Cronos',
    symbol: 'CRO',
    logo: <CronosLogoIcon />,
    description: 'Cronos',
  },
  [ Network.arbitrum ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Arbitrum',
    symbol: 'ETH',
    logo: <ArbitrumLogoIcon />,
    description: 'Arbitrum',
  },
  [ Network.nautilus ]: {
    paymentsDisabled: true,
    disabled: false,
    name: 'Nautilus Chain',
    symbol: 'ZBC',
    logo: <NautilusLogoIcon />,
    description: 'Nautilus Chain',
  },
  [ Network.eosEvm ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'EOS EVM',
    symbol: 'EOS',
    logo: <EosEvmLogoIcon />,
    description: 'EOS EVM',
  },
  [ Network.opBnb ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'opBNB',
    symbol: 'BNB',
    logo: <BinanceLogoIcon />,
    description: 'opBNB',
  },
  [ Network.greenfieldBnb ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Greenfield Bnb',
    symbol: 'BNB',
    logo: <BinanceLogoIcon />,
    description: 'Greenfield Bnb',
  },
  [ Network.base ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'BASE',
    symbol: 'ETH',
    logo: <BaseLogoIcon />,
    description: 'BASE',
  },
  [ Network.arthera ]: {
    paymentsDisabled: false,
    disabled: false,
    name: 'Arthera',
    symbol: 'AA',
    logo: <ArtheraLogoIcon />,
    description: 'Arthera',
  },
  [ Network.shardeum ]: {
    paymentsDisabled: true,
    disabled: true,
    name: 'Shardeum',
    symbol: 'SHM',
    logo: <ShardeumLogoIcon />,
    description: 'Shardeum',
  },
};
